version: '3.7'
services:
  zookeeper:
    image: docker.artifactory.tapsi.tech/confluentinc/cp-zookeeper:7.1.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: sn-zookeeper
    networks:
      - kafka-network

  kafka:
    image: docker.artifactory.tapsi.tech/confluentinc/cp-kafka:7.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    container_name: sn-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sn-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    networks:
      - kafka-network

  kafka-jmx-exporter:
    image: docker.artifactory.tapsi.tech/danielqsj/kafka-exporter:latest
    ports:
      - "9308:9308"
    depends_on:
      - kafka
    command: [ "--kafka.server=sn-kafka:29092" ]
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
