version: '3.7'

services:
  mongo:
    image: docker.artifactory.tapsi.tech/mongo:7.0
    container_name: local-mongo
    command: ["--replSet", "rs"]
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ../../../volumes/mongo-single-data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
