services:
  redis:
    image: docker.artifactory.tapsi.tech/bitnami/redis:7.4
    container_name: redis-single
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
